### ISSUE TITLE
Problem with running and dowloading video

### ISSUE THREAD

**Issue by greyhat94** [Ghost6446/StreamingCommunity_scraper#2]
Hi, I tried to run the python script, having installed the requirements beforehand. However, when I start the command prompt and open the script directory, typing the command "python run.py", I get the following error:

```
[16:44:10] Need to update to => v0.7                                                                        update.py:48
           Last version {'name': 'StreamingCommunity_scraper-main.zip', 'n_download': 37, 'msg': 'Upload    update.py:51
           domain ".at"'}
           Extract file                                                                                     update.py:57
           Clean ...                                                                                        update.py:65

           StreamingCommunity_scraper was downloaded 37 times, but only 5.41 of You(!) have starred it.     update.py:73
                   Help the repository grow today, by leaving a star on it and sharing it to others online!


[16:44:16] Close all instance of chrome                                                                       util.py:15
Traceback (most recent call last):
  File "C:\Users\umile\Desktop\StreamingCommunity_scraper-main\run.py", line 17, in <module>
    driver.create(True)
  File "C:\Users\umile\Desktop\StreamingCommunity_scraper-main\Stream\util\Driver.py", line 44, in create
    self.driver = webdriver.Chrome(options=self.options,  service=self.service)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\webdriver.py", line 218, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot create default profile directory
Stacktrace:
        GetHandleVerifier [0x01194DE3+43907]
        (No symbol) [0x01120741]
        (No symbol) [0x010133ED]
        (No symbol) [0x0103AEAF]
        (No symbol) [0x0103815E]
        (No symbol) [0x01035190]
        (No symbol) [0x01069396]
        (No symbol) [0x01068F2C]
        (No symbol) [0x01062956]
        (No symbol) [0x0103E17E]
        (No symbol) [0x0103F32D]
        GetHandleVerifier [0x01445AF9+2865305]
        GetHandleVerifier [0x0148E78B+3163435]
        GetHandleVerifier [0x01488441+3138017]
        GetHandleVerifier [0x0121E0F0+605840]
        (No symbol) [0x0112A64C]
        (No symbol) [0x01126638]
        (No symbol) [0x0112675F]
        (No symbol) [0x01118DB7]
        BaseThreadInitThunk [0x76197BA9+25]
        RtlInitializeExceptionChain [0x7789BD3B+107]
        RtlClearBits [0x7789BCBF+191]

```
How can I solve this problem? I am using the updated version of the script, and I do not understand why I cannot download the contents from the Stream Community site.

**Comment by Ghost6446** [comment]
Change in stream\util\driver.py :
self.options.add_argument('--user-data-dir=C:/Users/'+os.getlogin()+'/AppData/Local/Google/Chrome/User Data') 

with :
self.options.add_argument('--profile-directory=Default')
self.options.add_argument('--user-data-dir=C:/Temp/ChromeProfile')

Maybe it solve the problem

**Comment by Ghost6446** [comment]
And install chrome standard "https://www.google.it/intl/it/chrome/?brand=YTUH&gclid=Cj0KCQjwhfipBhCqARIsAH9msbnpliIuLJUah0TvZMU0S-ZL5eLh4QH9CEa2Wa-fpUsB01cA3IEmwGMaAmbvEALw_wcB&gclsrc=aw.ds"

**Comment by greyhat94** [comment]
I got this error: 

```
Traceback (most recent call last):
  File "C:\Users\umile\Desktop\StreamingCommunity_scraper-main\run.py", line 56, in <module>
    get_film(msg.ask("[cyan]Insert film key ").replace(" ", ""))
  File "C:\Users\umile\Desktop\StreamingCommunity_scraper-main\run.py", line 50, in get_film
    download(m3u8['url'], m3u8['data'], m3u8['req_header'], m3u8['key'], vid_id+".mp4")
  File "C:\Users\umile\Desktop\StreamingCommunity_scraper-main\Stream\util\m3u8.py", line 171, in download
    save_in_part("ou_ts", merged_mp4)
  File "C:\Users\umile\Desktop\StreamingCommunity_scraper-main\Stream\util\m3u8.py", line 79, in save_in_part
    save_part_ts(start, end, part)
  File "C:\Users\umile\Desktop\StreamingCommunity_scraper-main\Stream\util\m3u8.py", line 74, in save_part_ts
    f.write(f"file {ordered_ts_names[i]} \n")
```

How can I fix it?

**Comment by Ghost6446** [comment]
Video name ? 
I think you insert wrong key in input

**Comment by greyhat94** [comment]
The film's name is "The Burial". Its key is "6746".

**Comment by Ghost6446** [comment]
It work, try to install python 3,9 and openssl

**Comment by greyhat94** [comment]
I use Python 3.11.3. As for OpenSSL, do you mean the library pyOpenSSL or the software from this website: https://www.openssl.org/?  Thank you.

**Comment by greyhat94** [comment]
So, after installing OpenSSL, the script seems to be working fine. However, the next time I started the script via the command prompt, the code in the **'Driver.py'** file reset, and each time I had to replace the variable "self.options.add_argument('--user-data-dir=C:/Users/'+os.getlogin()+'/AppData/Local/Google/Chrome/User Data')" with this: "self.options.add_argument('--profile-directory=Default')
self.options.add_argument('--user-data-dir=C:/Temp/ChromeProfile')". How can I fix this issue?

**Comment by Ghost6446** [comment]
Change in file "__version__.py": 
__version__ = 'v0.6' with "__version__ = 'v0.7', in this way the script will not try to re upload all file, 
or go to util, os.py and change:
"if os.path.isfile(sfile):" with if "os.path.isfile(sfile) and sfile != "Driver.py",
but i think the first version will work.

**Comment by greyhat94** [comment]
Ok. Thank you for your help. I'll try to run it again and let you know if everything goes wrong.
