### ISSUE TITLE
problemi a unire i file ts

### ISSUE THREAD

**Issue by artifix100** [Ghost6446/StreamingCommunity_scraper#7]
grande lavoro , io non sono un esperto seguo solo attentamente le istruzioni e scaricando un film il processo si blocca all'unione delle centinaia di file ts della cartella temporanea questa la copia del log : 

Download 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 2.6/2.6 K [ 0:07:03 < 0:00:01 , 8 bytes/s ]
[22:18:58] All parts downloaded                                                                                      m3u8.py:187
Decoding   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/2,706  [ 0:00:00 < -:--:-- , ? it/s ]
Traceback (most recent call last):
  File "c:\Users\piern\Downloads\StreamingCommunity_scraper-main\run.py", line 141, in <module>
    get_film(vid_id=film_id)
  File "c:\Users\piern\Downloads\StreamingCommunity_scraper-main\run.py", line 92, in get_film
    donwload_m3u8(
  File "c:\Users\piern\Downloads\StreamingCommunity_scraper-main\Stream\util\m3u8.py", line 191, in donwload_m3u8
    video_decoder(ts_fname)
  File "c:\Users\piern\Downloads\StreamingCommunity_scraper-main\Stream\util\m3u8.py", line 43, in __call__
    self.decode_aes_128(video_fname)
  File "c:\Users\piern\Downloads\StreamingCommunity_scraper-main\Stream\util\m3u8.py", line 39, in decode_aes_128
    subprocess.run(["openssl","aes-128-cbc","-d","-in", video_fname,"-out", os.path.join("ou_ts", frame_name),"-nosalt","-iv", self.iv,"-K", self.uri ])
  File "C:\Users\piern\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piern\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\piern\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
PS C:\Users\piern>

**Comment by Ghost6446** [comment]
Mi sono dimenticato di aggiungere che deve aggiungere openssl and ffmpeg alle path di window

**Comment by artifix100** [comment]
innanzi tutto grazie della sollecita risposta , poi confermo che sembra risolto modificando variabile path . grazie mille chiudi pure

**Comment by artifix100** [comment]
azzz ho parlato troppo presto , per un film funziona ma per serie televisive no mi dà seguente errore

[11:00:20] Find system => win32                                                                                            run.py:126[11:00:21] Everything up to date                                                                                         update.py:77

           StreamingCommunity_scraper was downloaded 36 times, but only 30.56 of You(!) have starred it.                 update.py:80                   Help the repository grow today, by leaving a star on it and sharing it to others online!


[11:00:26] Install chrome driver                                                                                         driver.py:42[11:00:28] Close all instance of chrome                                                                                  driver.py:17           Create driver                                                                                                 driver.py:80
DevTools listening on ws://127.0.0.1:60721/devtools/browser/b3ad4f73-009a-46ad-a3dc-153c062128bb
Insert film key : 7375?e=48328
[11:01:11] Get page => https://streamingcommunity.cz/watch/7375?e=48328                                                  driver.py:87[0101/110111.488:WARNING:backend_impl.cc(1759)] Destroying invalid entry.
[0101/110111.978:ERROR:cert_verify_proc_builtin.cc(705)] CertVerifyProcBuiltin for streamingcommunity.cz failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0101/110113.519:ERROR:cert_verify_proc_builtin.cc(705)] CertVerifyProcBuiltin for madurird.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0101/110113.739:ERROR:cert_verify_proc_builtin.cc(705)] CertVerifyProcBuiltin for vixcloud.co failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0101/110114.473:ERROR:cert_verify_proc_builtin.cc(705)] CertVerifyProcBuiltin for analytics.vixcloud.co failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0101/110116.681:INFO:CONSOLE(77)] "Service Worker Registered", source: https://streamingcommunity.cz/watch/7375?e=48328 (77)
[0101/110116.868:ERROR:cert_verify_proc_builtin.cc(705)] CertVerifyProcBuiltin for sc-u1-01.scws-content.net failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0101/110117.105:ERROR:cert_verify_proc_builtin.cc(705)] CertVerifyProcBuiltin for www.googletagmanager.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[11:01:18] Find title => Watch Un inganno di troppo S1:E1                                                                   run.py:41           Find all info ...                                                                                                run.py:49[11:01:19] Film language => forced-ita                                                                                      run.py:82           Start download video ...                                                                                         run.py:90Traceback (most recent call last):
  File "C:\Users\piern\Downloads\StreamingCommunity_scraper-main\run.py", line 141, in <module>
    get_film(vid_id=film_id)
  File "C:\Users\piern\Downloads\StreamingCommunity_scraper-main\run.py", line 92, in get_film
    donwload_m3u8(
  File "C:\Users\piern\Downloads\StreamingCommunity_scraper-main\Stream\util\m3u8.py", line 147, in donwload_m3u8
    os.makedirs(temp_folder, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
NotADirectoryError: [WinError 267] Nome di directory non valido: 'temp_ts__Watch Un inganno di troppo S1:E1'
PS C:\Users\piern\Downloads\StreamingCommunity_scraper-main>

**Comment by Ghost6446** [comment]
Han okay, oggi pomeriggio risolvo. Nel mentre scrivimi serie,stagione ed ep.

**Comment by artifix100** [comment]
Oh grazie ho fatto un paio di tentativi il primo con "Grandi speranze" stagione uno ep 1 ( great expectations in inglese tit originale ) ma anche quello che vedi nel report.di sopra un inganno di troppo stagione uno EP 1 fa lo stesso errore

**Comment by Ghost6446** [comment]
Con questa version non si possono scaricare le serie, ho aggiunto la nuova repo dove si può scaricare sia film se serie
